import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { optimize } from 'svgo'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const packageRoot = path.resolve(__dirname, '..')
const assetsDir = path.join(packageRoot, 'assets')
const generatedDir = path.join(packageRoot, 'src', 'generated')
const legacyOutputFile = path.join(packageRoot, 'src', 'icons.tsx')
const sourceBanner = `/* eslint-disable */
/* auto-generated by packages/icons/scripts/build-icons.mjs */
/* do not edit this file directly */
`

function toPascalCase(value) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function toCamelCase(value) {
  const pascal = toPascalCase(value)
  return pascal ? pascal.charAt(0).toLowerCase() + pascal.slice(1) : pascal
}

function componentNameFromFile(fileName) {
  const baseName = fileName.replace(/\.svg$/i, '')
  return `${toPascalCase(baseName)}`
}

function componentFileNameFromFile(fileName) {
  const baseName = fileName.replace(/\.svg$/i, '')
  return `${toCamelCase(baseName)}.tsx`
}

function extractSvgAttribute(attributes, name) {
  const pattern = new RegExp(`${name}\\s*=\\s*["']([^"']+)["']`, 'i')
  const match = attributes.match(pattern)
  return match?.[1] ?? null
}

function indentMultiline(content, spaces) {
  const prefix = ' '.repeat(spaces)
  return content
    .trim()
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map(line => `${prefix}${line.trim()}`)
    .join('\n')
}

function parseSvg(content, fileName) {
  const normalized = content
    .replace(/^\uFEFF/, '')
    .replace(/<\?xml[\s\S]*?\?>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .trim()

  const match = normalized.match(/<svg\b([^>]*)>([\s\S]*?)<\/svg>/i)
  if (!match) {
    throw new Error(`无法解析 SVG 根节点: ${fileName}`)
  }

  const attributes = match[1] ?? ''
  const inner = (match[2] ?? '').trim()
  const viewBox = extractSvgAttribute(attributes, 'viewBox') ?? '0 0 16 16'

  return {
    viewBox,
    inner,
  }
}

async function collectSvgFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true })
  const directories = entries.filter(entry => entry.isDirectory()).map(entry => entry.name)

  if (directories.length > 0) {
    throw new Error(`assets 目录仅支持平铺 SVG，发现子目录: ${directories.join(', ')}`)
  }

  return entries
    .filter(entry => entry.isFile() && entry.name.toLowerCase().endsWith('.svg'))
    .map(entry => entry.name)
    .sort((a, b) => a.localeCompare(b))
}

async function readGeneratedFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => [])
  return entries.filter(entry => entry.isFile()).map(entry => entry.name)
}

async function writeIfChanged(filePath, nextContent) {
  const previousContent = await readFile(filePath, 'utf8').catch(() => null)
  if (previousContent === nextContent) {
    return 'unchanged'
  }

  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, nextContent, 'utf8')
  return previousContent === null ? 'created' : 'updated'
}

function generateComponentSource(icon) {
  return `${sourceBanner}

import type { JSX } from 'solid-js'

import { IconBase } from '../base'
import type { IconProps } from '../types'

export function ${icon.componentName}(props: IconProps): JSX.Element {
  return (
    <IconBase {...props} viewBox="${icon.viewBox}">
${indentMultiline(icon.inner, 6)}
    </IconBase>
  )
}`
}

function createIndexSource(icons) {
  return `${sourceBanner}

${icons.map(icon => `export * from './${icon.componentFileName.replace(/\.tsx$/, '')}'`).join('\n')}
`
}

function optimizeSvg(content, fileName) {
  const result = optimize(content, {
    path: fileName,
    multipass: true,
    plugins: ['preset-default'],
    js2svg: {
      pretty: true,
      indent: 2,
    },
  })

  if ('data' in result) {
    return result.data
  }

  throw new Error(`SVGO 优化失败: ${fileName}`)
}

async function readIcons() {
  const files = await collectSvgFiles(assetsDir)
  const icons = []

  for (const fileName of files) {
    const fullPath = path.join(assetsDir, fileName)
    const svgContent = await readFile(fullPath, 'utf8')
    const optimizedSvg = optimizeSvg(svgContent, fileName)
    const parsed = parseSvg(optimizedSvg, fileName)
    icons.push({
      fileName,
      componentName: componentNameFromFile(fileName),
      componentFileName: componentFileNameFromFile(fileName),
      viewBox: parsed.viewBox,
      inner: parsed.inner,
    })
  }

  return icons
}

function createExpectedFiles(icons) {
  const expectedFiles = new Map()

  for (const icon of icons) {
    expectedFiles.set(icon.componentFileName, generateComponentSource(icon))
  }

  expectedFiles.set('index.ts', createIndexSource(icons))
  return expectedFiles
}

async function syncGeneratedFiles(expectedFiles) {
  await mkdir(generatedDir, { recursive: true })
  await rm(legacyOutputFile, { force: true })

  const existingFiles = await readGeneratedFiles(generatedDir)
  const summary = {
    createdCount: 0,
    updatedCount: 0,
    unchangedCount: 0,
    removedCount: 0,
  }

  for (const existingFile of existingFiles) {
    if (expectedFiles.has(existingFile)) {
      continue
    }

    await rm(path.join(generatedDir, existingFile), { force: true })
    summary.removedCount++
  }

  for (const [relativePath, content] of expectedFiles) {
    const result = await writeIfChanged(path.join(generatedDir, relativePath), content)
    if (result === 'created') summary.createdCount++
    if (result === 'updated') summary.updatedCount++
    if (result === 'unchanged') summary.unchangedCount++
  }

  return summary
}

function reportResult(iconCount, summary) {
  console.log(
    [
      `Generated ${iconCount} icons -> ${path.relative(packageRoot, generatedDir)}`,
      `created=${summary.createdCount}`,
      `updated=${summary.updatedCount}`,
      `unchanged=${summary.unchangedCount}`,
      `removed=${summary.removedCount}`,
    ].join(', '),
  )
}

async function main() {
  const icons = await readIcons()
  const expectedFiles = createExpectedFiles(icons)
  const summary = await syncGeneratedFiles(expectedFiles)
  reportResult(icons.length, summary)
}

main().catch(error => {
  console.error(error)
  process.exitCode = 1
})
